import { Hero } from "@/components/Hero";
import { SafariCard } from "@/components/SafariCard";
import { DestinationCard } from "@/components/DestinationCard";
import { Testimonials } from "@/components/Testimonials";
import { FAQ } from "@/components/FAQ";
import { Button } from "@/components/ui/button";
import { safaris } from "@/data/safaris";
import { destinations } from "@/data/destinations";

export default function HomePage() { return <><Hero eyebrow="Victoria Falls & Chobe safari experiences" title="Journeys that feel personal." description="Discover Victoria Falls, Zimbabwe and Chobe, Botswana through local insight, trusted partners and a real love for the region." image="https://images.unsplash.com/photo-1523805009345-7448845a9e53?auto=format&fit=crop&w=2000&q=90"><div className="hero-actions"><Button href="/safaris">Explore safaris</Button><Button href="/contact" variant="secondary">Build your trip</Button></div></Hero><section className="section intro"><div className="container split"><div><p className="eyebrow">Welcome</p><h2>Your trusted guide to unforgettable safari experiences.</h2></div><p className="large-text">We create personalised journeys that match your pace, interests and dreams. Every detail is arranged to feel effortless, comfortable, safe and enriching.</p></div></section><section className="section section-tint"><div className="container"><div className="section-heading"><p className="eyebrow">Featured safaris</p><h2>Victoria Falls and Chobe itineraries</h2><p>Choose a set itinerary or create a journey around your preferred dates, stays and experiences.</p></div><div className="card-grid">{safaris.map(safari => <SafariCard key={safari.slug} safari={safari} />)}</div></div></section><section className="section"><div className="container"><div className="section-heading"><p className="eyebrow">Destinations</p><h2>Places with local meaning</h2></div><div className="tile-grid">{destinations.map(destination => <DestinationCard key={destination.slug} destination={destination} />)}</div></div></section><Testimonials /><section className="section"><div className="container split faq-split"><div><p className="eyebrow">Good to know</p><h2>Safari questions, answered.</h2><p>We keep planning clear before you commit, then refine each detail together.</p><Button href="/faq">View all questions</Button></div><FAQ /></div></section></>; }
